# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: abe9c21244ad46979f6b944c424703d49c2bdbf66175ea51f78708efc5ceedec5f917443b5dec5f9438f14399919fd9cd69cf6f29204453bcd4b73dc05d8a132

test:
  secret_key_base: 52ef8c1c86fa4696fceec9ebb64c1b60de7314389a1220869fc6c4df04c077059ec0c06c82c33a60081383f0e61f34aa5758729e4f5b4650ae3fe5971d48b23a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
